### ISSUE TITLE
Date replacement fails if timestamp changes length

### ISSUE THREAD

**Issue by Strikeskids** [bradfitz/gitbrute#8]
See line https://github.com/bradfitz/gitbrute/blob/13370008385255de5f7ed0f744827104ca474b10/gitbrute.go#L117

This replaces the timestamps as decimal strings directly. If the number of digits in the unix timestamp changes during the brute-force attempt, this will incorrectly replace the string.

This is a minor issue, as it will only occur pre 2002 or in 2286. This would be especially applicable to #5 if git had been created back then.

**Comment by bradfitz** [comment]
You are correct and I hereby award you Internet points. Unfortunately (or fortunately), this project is kinda a joke and I don't want to maintain it, so.... I'm going to close this. But thanks! Now at least I can refer to it if others file the same bug and I'll tell them you won the Internet first.  :-)
